---

- name: Get git sources
  ansible.builtin.git:
    repo: '{{ gitlab_gitaly_repository }}'
    dest: '{{ gitlab_git_prefix }}/srv/gitaly'
    version: '{{ gitlab_repository_version }}'
  register: gitaly_changed

- name: Compile and install Git
  ansible.builtin.command: make git GIT_PREFIX={{ gitlab_git_prefix }}
  args:
    chdir: '{{ gitlab_git_prefix }}/srv/gitaly'
  when: gitaly_changed.changed or gitlab_gitaly_force_rebuild
  tags:
    - skip_ansible_lint
