---

- name: Ensures backup path exists
  ansible.builtin.file:
    path: '{{ gitlab_backup_path }}'
    state: directory
    mode: '{{ gitlab_backup_path_mode }}'
    owner: '{{ gitlab_backup_owner }}'
    group: '{{ gitlab_backup_group }}'
  when: not gitlab_manage_backup_path

- name: Create systemd timer for backup job
  ansible.builtin.include_role:
    name: alphanodes.setup.systemd_timer
  vars:
    timers:
      gitlab-backup:
        on_calendar: '{{ gitlab_backup_on_calendar }}'
        exec_start: "{{ gitlab_backup_command }}"
        syslog_identifier: gitlab-backup

- name: Manage systemd timer for registry garbage collection
  ansible.builtin.include_role:
    name: alphanodes.setup.systemd_timer
  vars:
    timers:
      gitlab-registry-gc:
        state: "{{ 'present' if gitlab_registry_gc_enabled else 'absent' }}"
        on_calendar: '{{ gitlab_registry_gc_on_calendar }}'
        exec_start: "{{ gitlab_registry_gc_command }}"
        syslog_identifier: gitlab-registry-gc
