---
- name: Create disable transparent hugepages systemd service file
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/systemd/system/disable-transparent-hugepages.service
    mode: 0644
  with_first_found:
    - "disable-transparent-hugepages.{{ ansible_distribution | lower }}.service.j2"
    - "disable-transparent-hugepages.{{ ansible_os_family | lower }}.service.j2"
  notify:
    - Run disable-transparent-hugepages
  when:
    - mongodb_disable_transparent_hugepages | bool
