---
# defaults file for postgresql client

# if yes, postgresql.org packages are used, else distribution packages
postgresql_client_use_repo: true

# which version should be used?
# if postresql role (server) is available, this version is used
# possible values: 10, 11, 12, 13, 14 or 15
postgresql_client_version: "{{ postgresql_version | default('14') }}"
postgresql_client_packages:
 - postgresql-client-{{ postgresql_version | default(postgresql_client_version) }}
 - python3-psycopg2

postgresql_repo_key_url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
postgresql_repo_protocol: https
postgresql_repo_url: 'deb {{ postgresql_repo_protocol }}://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main'

postgresq_skip_apt_key: false
