---

- name: Include setup tasks
  ansible.builtin.import_tasks: setup.yml
  tags: unbound
  when: not unbound_remove | bool

- name: Include remove tasks
  ansible.builtin.import_tasks: remove.yml
  tags: unbound
  when: unbound_remove | bool
