---

matomo_working_dir: /tmp/matomo_source

matomo_available_plugins:
  CustomVariables:
    use_git: true
    repo: https://github.com/matomo-org/plugin-CustomVariables.git
    download: https://github.com/matomo-org/plugin-CustomVariables/archive/%%version%%.tar.gz
    version: 4.1.3
  QueuedTracking:
    use_git: false
    repo: https://github.com/matomo-org/plugin-QueuedTracking.git
    download: https://github.com/matomo-org/plugin-QueuedTracking/archive/%%version%%.tar.gz
    version: 4.0.7
  LoginLdap:
    use_git: true
    repo: https://github.com/matomo-org/plugin-LoginLdap.git
    download: https://github.com/matomo-org/plugin-LoginLdap/archive/%%version%%.tar.gz
    version: 4.7.3
    branch: 4.7.3
  LoginShibboleth:
    use_git: true
    repo: https://github.com/uniwue-rz/LoginShibboleth.git
    download: https://github.com/uniwue-rz/LoginShibboleth/archive/%%version%%.tar.gz
    version: 1.2.1
  Migration:
    use_git: true
    repo: https://github.com/matomo-org/plugin-Migration.git
    download: https://github.com/matomo-org/plugin-Migration/archive/%%version%%.tar.gz
    version: 4.0.2
  Provider:
    use_git: true
    repo: https://github.com/matomo-org/plugin-Provider.git
    download: https://github.com/matomo-org/plugin-Provider/archive/%%version%%.tar.gz
    version: 4.0.5
  SecurityInfo:
    use_git: true
    repo: https://github.com/matomo-org/plugin-SecurityInfo.git
    download: https://github.com/matomo-org/plugin-SecurityInfo/archive/%%version%%.tar.gz
    version: 4.0.2
