---

matomo_packages:
  # - php-geoip
  - php8.5-ldap
  - php8.5-mbstring
  - php8.5-xml
  - php8.5-gd

matomo_php_mods_available: /etc/php/8.5/mods-available

matomo_redis_php_packages:
  - php8.5-redis
  - php8.5-igbinary
