---
# handlers file for unbound

- name: Restart unbound
  ansible.builtin.systemd_service:
    name: unbound
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
