---

- name: Include setup tasks
  ansible.builtin.include_tasks: setup.yml
  tags:
    - nodejs
  when: not nodejs_remove

- name: Include remove tasks
  ansible.builtin.import_tasks: remove.yml
  tags:
    - nodejs
  when: nodejs_remove
