---

- name: Cleanup systemd configuration
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - /etc/systemd/system/puma-{{ instance_name }}.service
    - /etc/systemd/system/multi-user.target.wants/puma-{{ instance_name }}.service
  notify:
    - Reload systemd daemon

- name: Cleanup nginx configuration
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - /etc/nginx/sites-available/{{ instance_name }}.conf
    - /etc/nginx/sites-enabled/{{ instance_name }}.conf
  when: redmine_with_nginx
  notify:
    - Restart nginx
