---

- name: Update redmine configuration {{ redmine_config_template.name }}
  ansible.builtin.template:
    src: redmine/config/{{ redmine_config_template.name }}.j2
    dest: '{{ redmine_config_dir }}/{{ redmine_config_template.name }}'
    owner: '{{ redmine_instance_name }}'
    group: '{{ redmine_instance_name }}'
    mode: '{{ redmine_config_template.mode | default(omit) }}'

- name: Get link info - {{ redmine_instance_name }}
  ansible.builtin.stat:
    path: '{{ redmine_app_dir }}/config/{{ redmine_config_template.name }}'
  register: file_info

- name: Remove redmine configuration file, if not a link - {{ redmine_instance_name }}
  ansible.builtin.file:
    path: '{{ redmine_app_dir }}/config/{{ redmine_config_template.name }}'
    state: absent
  when:
    - file_info.stat.islnk is defined
    - not file_info.stat.islnk

- name: Symlinks to redmine/config - {{ redmine_instance_name }}
  ansible.builtin.file:
    src: '{{ redmine_config_dir }}/{{ redmine_config_template.name }}'
    dest: '{{ redmine_app_dir }}/config/{{ redmine_config_template.name }}'
    state: link
  become: false
  become_user: '{{ redmine_user }}'
  when: redmine_config_template.link
