---

- name: Run composer for roundcube
  ansible.builtin.command: composer update --no-dev --no-scripts -n
  args:
    chdir: '{{ roundcube_htdocs }}'
  environment:
    COMPOSER_ALLOW_SUPERUSER: '1'

- name: Update roundcube js
  ansible.builtin.command: bin/install-jsdeps.sh
  args:
    chdir: '{{ roundcube_htdocs }}'
