---
# defaults file for sudo

sudo_packages:
  - sudo

sudo_sudoers: []

# if no, /etc/sudoers is untouched
sudo_manange_sudoers_config: true

# Set defaults
# e.g.
# - ':ansible  env_keep += "PATH LD_LIBRARY_PATH LIBRARY_PATH"'
# - ':ansible  !requiretty'
sudo_defaults:
  - ' env_keep += "ftp_proxy http_proxy https_proxy no_proxy SSH_AUTH_SOCK"'

sudo_group_sudo_active: true
sudo_group_sudo_without_password: false
sudo_group_wheel_active: false
sudo_group_wheel_without_password: false
