---

- name: Create roundcube database
  ansible.builtin.include_role:
    name: alphanodes.setup.mysql
    tasks_from: create_database.yml
  vars:
    mysql_setup_db_name: '{{ roundcube_db_name }}'

- name: Create roundcube database user
  ansible.builtin.include_role:
    name: alphanodes.setup.mysql
    tasks_from: create_user.yml
  vars:
    mysql_setup_db_name: '{{ roundcube_db_name }}'
    mysql_setup_user_name: '{{ roundcube_db_user }}'
    mysql_setup_user_password: '{{ roundcube_db_password }}'
    mysql_setup_user_host: '{{ roundcube_db_host }}'
    mysql_setup_salt_id: roundcube

- name: Apply pending composer/js handlers before DB migration
  ansible.builtin.meta: flush_handlers

- name: Update roundcube database schema
  ansible.builtin.command: bin/updatedb.sh --package=roundcube --dir=SQL
  args:
    chdir: '{{ roundcube_htdocs }}'
  register: rcmail_updatedb
  changed_when: "'Updating database schema' in rcmail_updatedb.stdout"
  when: roundcube_git_install
