---
- name: Include vars
  ansible.builtin.import_tasks: include-vars.yml

- name: Include setup tasks
  ansible.builtin.include_tasks: setup.yml
  tags:
    - nextcloud

- name: Include MySQL tasks
  ansible.builtin.include_tasks: mysql.yml
  tags:
    - nextcloud
    - mysql
  when: nextcloud_db_type == 'mysql'

- name: Include PostgreSQL tasks
  ansible.builtin.include_tasks: postgresql.yml
  tags:
    - nextcloud
    - postgresql
  when: nextcloud_db_type == 'pgsql'
