---

- name: Remove glances venv
  ansible.builtin.file:
    path: '{{ python_venv_parent }}/{{ glances_pip_venv }}'
    state: absent

- name: Remove glance package
  ansible.builtin.apt:
    name: '{{ glances_packages }}'
    state: absent
  become: true
