---

- name: Use pip
  when: glances_with_pip
  block:
    - name: Include pip role
      ansible.builtin.include_role:
        name: alphanodes.setup.pip

    - name: Be sure glances not installed with debian packages
      ansible.builtin.apt:
        name: glances
        state: absent

    - name: Install pip modules
      ansible.builtin.pip:
        name: '{{ glances_pip_modules }}'
        state: present

- name: Use debian package
  when: not glances_with_pip
  block:
    - name: Be sure glaces package are installed
      ansible.builtin.apt:
        name: '{{ glances_packages }}'
        state: present
