---

- name: Restart apt-daily.timer
  ansible.builtin.systemd:
    name: apt-daily.timer
    state: restarted

- name: Restart apt-daily-upgrade.timer
  ansible.builtin.systemd:
    name: apt-daily-upgrade.timer
    state: restarted
