---
- name: Include vars
  ansible.builtin.import_tasks: include-vars.yml

- name: Include setup tasks
  ansible.builtin.include_tasks: setup.yml
  tags: matomo

- name: Include MySQL tasks
  ansible.builtin.include_tasks: mysql.yml
  tags: matomo
  when: matomo_with_mysql
