---

- name: Import setup tasks
  ansible.builtin.import_tasks: setup.yml
  tags: sphinx

- name: Include instance tasks
  ansible.builtin.include_tasks: instance.yml
  tags: sphinx
  loop: "{{ sphinx_instances }}"
  loop_control:
    loop_var: instance
  when: instance.state is undefined or instance.state == 'active'
