---

- name: Be sure sphinx required packages are installed
  ansible.builtin.apt:
    name: '{{ sphinx_packages }}'
    state: present

- name: Be sure pip and sphinx not installed with debian packages
  ansible.builtin.apt:
    name: '{{ sphinx_unwanted_packages }}'
    state: absent

- name: Include python role
  ansible.builtin.include_role:
    name: alphanodes.setup.python
  vars:
    python_pip_packages: '{{ sphinx_pip_packages }}'
