---

python_packages:
  - python3-pip
  - python3-virtualenv

python_with_dev: false

# pip executable name, if not set the ansible/system default is used
# python_pip_executable: pip3

# Packages to install with pip, either plain names or items with
# name, version, state (e.g. absent, latest, forcereinstall) and virtualenv.
# Example:
# python_pip_packages:
#   - docker
#   - name: awscli
#     version: "1.11.91"
#   - name: docker
#     virtualenv: /my_app/venv
python_pip_packages: []

python_pip_default_state: latest
python_pip_virtualenv_site_packages: false

# python_pip_default_venv: yourenv

python_venv_parent: "{{ ansible_facts['env']['HOME'] }}/.venvs"
