---

- name: Include mongodb tasks
  ansible.builtin.include_tasks: mongodb.yml
  tags:
    - rocketchat
    - mongodb
  when: not rocketchat_remove

- name: Include setup tasks
  ansible.builtin.include_tasks: setup.yml
  tags: rocketchat
  when: not rocketchat_remove

- name: Include remove tasks
  ansible.builtin.import_tasks: remove.yml
  tags: rocketchat
  when: rocketchat_remove
