---

# alphanodes.mongodb use deprecated apt_key
- name: Add mongodb gpg key
  ansible.builtin.get_url:
    url: "{{ rocketchat_mongodb_apt_key_url }}"
    dest: /etc/apt/trusted.gpg.d/mongodb.asc
    mode: 0644
    force: true

- name: Include mongodb role
  ansible.builtin.include_role:
    name: alphanodes.setup.mongodb
  when: rocketchat_with_mongodb

- name: Ensure the MongoDB replSets have been initiated
  ansible.builtin.shell: >-
    mongo --quiet --eval
    'JSON.stringify(rs.initiate({_id:"{{ mongodb_replication_replset }}",
    members: [{"_id":1, "host":
    "{{ rocketchat_mongodb_server }}:{{ rocketchat_mongodb_port }}"}]}))'
  become: true
  become_user: "{{ mongodb_user | default('mongodb') }}"
  args:
    executable: /bin/bash
  register: repl_result
  changed_when:
    - not (repl_result.stdout is search(' Object'))
    - ('ok' in (repl_result.stdout | from_json))
    - (((repl_result.stdout | from_json).ok | int) == 1)
