---
dependencies:
  - role: alphanodes.setup.common
  - role: alphanodes.setup.rsync
    when: not gitlab_remove
  - role: alphanodes.setup.ssl
    when: not gitlab_remove
  - role: alphanodes.setup.redis_server
    when: not gitlab_remove
  - role: alphanodes.setup.nginx
    when: not gitlab_remove
  - role: alphanodes.setup.postgresql
    when: not gitlab_remove

galaxy_info:
  description: Setup gitlab
  author: alexandermeindl
  company: AlphaNodes GmbH
  license: Apache License 2.0
  min_ansible_version: '2.14'
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
  galaxy_tags:
    - gitlab
    - git
    - server
