# defaults file for # defaults file for sphinx
---

# all instances are stored there
sphinx_base_dir: /srv/sphinx

# if you want a specific version. do not set means latest version
# sphinx_version: 1.7.5

sphinx_packages:
  - build-essential
  - texlive-latex-recommended
  - texlive-fonts-recommended
  # texlive-latex-extra requires python 2.7 :( - but we need it for PDF creation
  - texlive-latex-extra
  - texlive-lang-german
  - latexmk

sphinx_unwanted_packages:
  - sphinx-common
  - python-pip
  - python3-pip

sphinx_pip_packages:
  - sphinx_rtd_theme
  - myst-parser
  - sphinx-copybutton
  - asciinema
  - sphinxcontrib-httpdomain

sphinx_instances: []

sphinx_always_build: false
