---
- name: Include vars
  ansible.builtin.import_tasks: include-vars.yml

- name: Include setup tasks
  ansible.builtin.include_tasks: setup.yml
  tags:
    - drupal

- name: Include instance tasks
  ansible.builtin.include_tasks: instance.yml
  tags:
    - drupal
  loop: "{{ drupal_instances }}"
  loop_control:
    loop_var: instance
  when: >
    instance.state is undefined
    or instance.state == 'active'
