---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 600

  vars:
    pip_install_packages:
      # Test installing a specific version of a package.
      - name: ipaddress
        version: '1.0.18'
      - 'pymongo'

  roles:
    - role: alphanodes.setup.python
