---
- name: Define memcached_user.
  ansible.builtin.set_fact:
    memcached_user: "{{ __memcached_user }}"
  when: memcached_user is not defined

- name: Install Memcached.
  ansible.builtin.package:
    name: memcached
    state: present
  register: memcached_install

# Configure Memcached.
- name: Copy Memcached configuration.
  ansible.builtin.template:
    src: memcached.conf.j2
    dest: "{{ memcached_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart memcached

- name: Ensure Memcached is started and set to run on startup.
  ansible.builtin.service:
    name: memcached
    state: started
    enabled: yes
