---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 600
      changed_when: false

  tasks:
    - name: "Include ansible-role-mongodb"
      ansible.builtin.include_role:
        name: alphanodes.setup.mongodb
  vars:
    mongodb_package: "{{ lookup('env','MONGODB_PACKAGE') }}"
    mongodb_version: "{{ lookup('env','MONGODB_VERSION') }}"
    mongodb_security_authorization: "{{ lookup('env', 'AUTH_STATE') }}"
    mongodb_replication_replset: "{{ lookup('env', 'REPLICASET') }}"
    mongodb_storage_dbpath: /var/lib/mongodb
    mongodb_net_bindip: 0.0.0.0
    mongodb_login_host: "{{ hostvars[groups['mongo_master'][0]].ansible_default_ipv4.address }}"

    mongodb_users:
      - {
        name: testUser,
        password: passw0rd,
        roles: readWrite,
        database: admin
      }
