---
- name: Install prerequisite packages
  hosts: all
  remote_user: root
  become: true
  tasks:
    - name: Install prerequisite packages for molecule testing on Debian or Ubuntu
      ansible.builtin.apt:
        update_cache: true
        name:
          - gpg
          - dirmngr
